# Generated by Django 3.1.2 on 2020-10-15 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title provided', max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('results_declared', models.BooleanField(default=False)),
                ('max_team_size', models.IntegerField(default=10)),
                ('slug', models.SlugField()),
                ('organizers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_organizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(default='No title provided.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team_id', models.CharField(max_length=50)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_teams', to='core.hackathon')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_a_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams_as_a_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hackathon')),
                ('links', models.ManyToManyField(to='core.Link')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
