# Generated by Django 3.1.2 on 2020-10-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='max_score',
        ),
    ]
