# Generated by Django 3.1.2 on 2020-10-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201011_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='status',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_team_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='No title provided.', max_length=50),
        ),
    ]
