# Generated by Django 3.1.2 on 2020-10-26 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201026_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
