# Generated by Django 3.1.2 on 2020-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201026_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='SMNP2G94BumV', editable=False, max_length=12),
        ),
    ]
