# Generated by Django 3.1.2 on 2020-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201026_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='GKoUgiNau5KdjRSr', max_length=16),
        ),
    ]
