# Generated by Django 3.1.2 on 2020-10-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201026_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='GKbwdMKyR9PBmxgU', max_length=16),
        ),
    ]
