# Generated by Django 3.1.4 on 2020-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201026_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
