# Generated by Django 3.1.4 on 2020-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201026_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
