# Generated by Django 3.1.4 on 2021-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201224_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
