# Generated by Django 3.1.2 on 2021-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210123_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review',
            field=models.TextField(default='There had been no reviews till now.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_url',
            field=models.URLField(default='EMPTY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='No title provided', max_length=150),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
