# Generated by Django 3.1.2 on 2021-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210126_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
