# Generated by Django 3.1.4 on 2020-12-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201014_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoURL',
            field=models.URLField(default='', max_length=400),
        ),
    ]
